In [1]:
# Dependencies
import pandas as pd
from pathlib import Path

In [16]:
games_details_path = Path('games_details.csv')
games_path = ('games.csv')

In [28]:
games_details = pd.read_csv(games_details_path)
games_details

/var/folders/bb/4gpn5xfn0dqcx7v7w_7s2llc0000gn/T/ipykernel_94670/2683507017.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  games_details = pd.read_csv(games_details_path)

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668623,11200005,1610612743,DEN,Denver,202706,Jordan Hamilton,NaN,NaN,NaN,19,...,0.0,2.0,2.0,0.0,2.0,0.0,1.0,3.0,17.0,NaN
668624,11200005,1610612743,DEN,Denver,202702,Kenneth Faried,NaN,NaN,NaN,23,...,1.0,0.0,1.0,1.0,1.0,0.0,3.0,3.0,18.0,NaN
668625,11200005,1610612743,DEN,Denver,201585,Kosta Koufos,NaN,NaN,NaN,15,...,3.0,5.0,8.0,0.0,1.0,0.0,0.0,3.0,6.0,NaN
668626,11200005,1610612743,DEN,Denver,202389,Timofey Mozgov,NaN,NaN,NaN,19,...,1.0,2.0,3.0,1.0,0.0,0.0,4.0,2.0,2.0,NaN
668627,11200005,1610612743,DEN,Denver,201951,Ty Lawson,NaN,NaN,NaN,27,...,0.0,2.0,2.0,6.0,2.0,0.0,6.0,1.0,8.0,NaN

In [17]:
games = pd.read_csv(games_path)
games.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2022-12-22,22200477,Final,1610612740,1610612759,2022,1610612740,126.0,0.484,0.926,...,25.0,46.0,1610612759,117.0,0.478,0.815,0.321,23.0,44.0,1
1,2022-12-22,22200478,Final,1610612762,1610612764,2022,1610612762,120.0,0.488,0.952,...,16.0,40.0,1610612764,112.0,0.561,0.765,0.333,20.0,37.0,1
2,2022-12-21,22200466,Final,1610612739,1610612749,2022,1610612739,114.0,0.482,0.786,...,22.0,37.0,1610612749,106.0,0.470,0.682,0.433,20.0,46.0,1
3,2022-12-21,22200467,Final,1610612755,1610612765,2022,1610612755,113.0,0.441,0.909,...,27.0,49.0,1610612765,93.0,0.392,0.735,0.261,15.0,46.0,1
4,2022-12-21,22200468,Final,1610612737,1610612741,2022,1610612737,108.0,0.429,1.000,...,22.0,47.0,1610612741,110.0,0.500,0.773,0.292,20.0,47.0,0

In [61]:
season_2022 = games[games['SEASON'] == 2022]['GAME_ID'].unique()
season_2022

array([22200477, 22200478, 22200466, 22200467, 22200468, 22200469,
       22200470, 22200471, 22200472, 22200473, 22200474, 22200475,
       22200476, 22200461, 22200462, 22200463, 22200464, 22200465,
       22200452, 22200453, 22200454, 22200455, 22200456, 22200457,
       22200458, 22200459, 22200460, 22200445, 22200446, 22200447,
       22200448, 22200449, 22200450, 22200451, 22200438, 22200439,
       22200440, 22200441, 22200442, 22200443, 22200444, 22200428,
       22200429, 22200430, 22200431, 22200432, 22200433, 22200434,
       22200435, 22200436, 22200437, 22200424, 22200425, 22200426,
       22200427, 22200414, 22200415, 22200416, 22200417, 22200418,
       22200419, 22200420, 22200421, 22200422, 22200423, 22200409,
       22200410, 22200411, 22200412, 22200413, 22200402, 22200403,
       22200404, 22200405, 22200406, 22200407, 22200408, 22200395,
       22200396, 22200397, 22200398, 22200399, 22200400, 22200401,
       22200387, 22200388, 22200389, 22200390, 22200391, 22200392,
       22200393, 22200394, 22200377, 22200378, 22200379, 22200380,
       22200381, 22200382, 22200383, 22200384, 22200385, 22200386,
       22200374, 22200375, 22200376, 22200363, 22200364, 22200365,
       22200366, 22200367, 22200368, 22200369, 22200370, 22200371,
       22200372, 22200373, 22200360, 22200361, 22200362, 22200352,
       22200353, 22200354, 22200355, 22200356, 22200357, 22200358,
       22200359, 22200344, 22200345, 22200346, 22200347, 22200348,
       22200349, 22200350, 22200351, 22200337, 22200338, 22200339,
       22200340, 22200341, 22200342, 22200343, 22200326, 22200327,
       22200328, 22200329, 22200330, 22200331, 22200332, 22200333,
       22200334, 22200335, 22200336, 22200325, 22200312, 22200313,
       22200314, 22200315, 22200316, 22200317, 22200318, 22200319,
       22200320, 22200321, 22200322, 22200323, 22200324, 22200309,
       22200310, 22200311, 22200299, 22200300, 22200301, 22200302,
       22200303, 22200304, 22200305, 22200306, 22200307, 22200308,
       22200290, 22200291, 22200292, 22200293, 22200294, 22200295,
       22200296, 22200297, 22200298, 22200286, 22200287, 22200288,
       22200289, 22200272, 22200273, 22200274, 22200275, 22200276,
       22200277, 22200278, 22200279, 22200280, 22200281, 22200282,
       22200283, 22200284, 22200285, 22200260, 22200261, 22200262,
       22200263, 22200264, 22200265, 22200266, 22200267, 22200268,
       22200269, 22200270, 22200271, 22200256, 22200257, 22200258,
       22200259, 22200248, 22200249, 22200250, 22200251, 22200252,
       22200253, 22200254, 22200255, 22200240, 22200241, 22200242,
       22200243, 22200244, 22200245, 22200246, 22200247, 22200235,
       22200237, 22200238, 22200239, 22200224, 22200225, 22200226,
       22200227, 22200228, 22200229, 22200230, 22200231, 22200232,
       22200233, 22200234, 22200221, 22200222, 22200223, 22200211,
       22200212, 22200213, 22200214, 22200215, 22200216, 22200217,
       22200218, 22200219, 22200220, 22200206, 22200207, 22200208,
       22200209, 22200210, 22200199, 22200200, 22200201, 22200202,
       22200203, 22200204, 22200205, 22200192, 22200193, 22200194,
       22200195, 22200196, 22200197, 22200198, 22200184, 22200185,
       22200186, 22200187, 22200188, 22200189, 22200190, 22200191,
       22200176, 22200177, 22200178, 22200179, 22200180, 22200181,
       22200182, 22200183, 22200172, 22200173, 22200174, 22200175,
       22200161, 22200159, 22200160, 22200162, 22200163, 22200164,
       22200165, 22200166, 22200167, 22200168, 22200169, 22200170,
       22200171, 22200144, 22200145, 22200146, 22200147, 22200148,
       22200149, 22200150, 22200151, 22200152, 22200153, 22200154,
       22200155, 22200156, 22200157, 22200158, 22200140, 22200141,
       22200142, 22200143, 22200132, 22200133, 22200134, 22200135,
       22200136, 22200137, 22200138, 22200139, 22200120, 22200121,
       22200122, 22200123, 22200124, 22200125, 22200126, 22200127,
       22200128, 22200129, 22200130, 22200131, 22200118, 22200119,
       22200108, 22200107, 22200109, 22200110, 22200111, 22200112,
       22200113, 22200114, 22200115, 22200116, 22200117, 22200103,
       22200104, 22200105, 22200106, 22200096, 22200097, 22200098,
       22200099, 22200100, 22200101, 22200102, 22200088, 22200089,
       22200090, 22200091, 22200092, 22200093, 22200094, 22200095,
       22200081, 22200082, 22200083, 22200084, 22200085, 22200086,
       22200087, 22200070, 22200071, 22200072, 22200073, 22200074,
       22200075, 22200076, 22200077, 22200078, 22200079, 22200080,
       22200066, 22200067, 22200068, 22200069, 22200056, 22200057,
       22200058, 22200059, 22200060, 22200061, 22200062, 22200063,
       22200064, 22200065, 22200052, 22200053, 22200054, 22200055,
       22200044, 22200045, 22200046, 22200047, 22200048, 22200049,
       22200050, 22200051, 22200037, 22200038, 22200039, 22200040,
       22200041, 22200042, 22200043, 22200028, 22200029, 22200030,
       22200031, 22200032, 22200033, 22200034, 22200035, 22200036,
       22200017, 22200018, 22200019, 22200020, 22200021, 22200022,
       22200023, 22200024, 22200025, 22200026, 22200027, 22200015,
       22200016, 22200003, 22200004, 22200005, 22200006, 22200007,
       22200008, 22200009, 22200010, 22200011, 22200012, 22200013,
       22200014, 22200001, 22200002, 12200062, 12200063, 12200064,
       12200065, 12200066, 12200067, 12200068, 12200069, 12200070,
       12200060, 12200061, 12200052, 12200053, 12200054, 12200055,
       12200056, 12200057, 12200058, 12200059, 12200047, 12200048,
       12200049, 12200050, 12200051, 12200043, 12200044, 12200045,
       12200046, 12200037, 12200039, 12200040, 12200041, 12200042,
       12200036, 12200029, 12200030, 12200031, 12200032, 12200033,
       12200034, 12200035, 12200023, 12200024, 12200026, 12200028,
       12200018, 12200019, 12200020, 12200021, 12200022, 12200014,
       12200015, 12200016, 12200017, 12200009, 12200010, 12200011,
       12200012, 12200013, 12200004, 12200005, 12200006, 12200007,
       12200003, 12200001])

In [63]:
season_2022_details = games_details[games_details['GAME_ID'].isin(season_2022)].dropna(subset=['START_POSITION'])
season_2022_details

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14639,12200001,1610612764,WAS,Washington,1628398,Kyle Kuzma,Kyle,F,NaN,20:04,...,0.0,4.0,4.0,1.0,0.0,1.0,3.0,3.0,7.0,-11.0
14640,12200001,1610612764,WAS,Washington,1629060,Rui Hachimura,Rui,F,NaN,25:10,...,0.0,9.0,9.0,0.0,1.0,0.0,1.0,0.0,13.0,-3.0
14641,12200001,1610612764,WAS,Washington,204001,Kristaps Porzingis,Kristaps,C,NaN,21:15,...,0.0,4.0,4.0,4.0,4.0,1.0,1.0,5.0,7.0,1.0
14642,12200001,1610612764,WAS,Washington,203078,Bradley Beal,Bradley,G,NaN,17:34,...,2.0,0.0,2.0,3.0,2.0,0.0,2.0,1.0,9.0,0.0
14643,12200001,1610612764,WAS,Washington,1628420,Monte Morris,Monte,G,NaN,18:19,...,1.0,0.0,1.0,5.0,1.0,0.0,2.0,3.0,9.0,-6.0

In [18]:
games.shape[0]

26651

In [37]:
games_details.columns.to_list()

['GAME_ID',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'TEAM_CITY',
 'PLAYER_ID',
 'PLAYER_NAME',
 'NICKNAME',
 'START_POSITION',
 'COMMENT',
 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TO',
 'PF',
 'PTS',
 'PLUS_MINUS']

In [15]:
games_details.shape[0]

668628

In [56]:
games_2022_array = games[games['GAME_DATE_EST'].str.startswith('2022')]['GAME_ID'].unique()
games_2022_array

array([22200477, 22200478, 22200466, ..., 22100542, 22100543, 22100544])

In [27]:
games_details_2022 = games_details[games_details['GAME_ID'].isin(games_2022_array)]
games_details_2022

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34834,22100544,1610612762,UTA,Utah,1630215,Jared Butler,Jared,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34835,22100544,1610612762,UTA,Utah,1630238,Malik Fitts,Malik,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34836,22100544,1610612762,UTA,Utah,1630235,Trent Forrest,Trent,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34837,22100544,1610612762,UTA,Utah,1630190,Elijah Hughes,Elijah,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34838,22100544,1610612762,UTA,Utah,1629671,Miye Oni,Miye,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
starters = games_details_2022.dropna(subset=['START_POSITION'])
starters

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34826,22100544,1610612762,UTA,Utah,202711,Bojan Bogdanovic,Bojan,F,NaN,35:00,...,1.0,5.0,6.0,1.0,1.0,0.0,2.0,0.0,20.0,-6.0
34827,22100544,1610612762,UTA,Utah,1626220,Royce O'Neale,Royce,F,NaN,35:56,...,2.0,2.0,4.0,2.0,0.0,0.0,1.0,3.0,15.0,-1.0
34828,22100544,1610612762,UTA,Utah,203497,Rudy Gobert,Rudy,C,NaN,34:59,...,7.0,12.0,19.0,2.0,0.0,0.0,2.0,4.0,20.0,10.0
34829,22100544,1610612762,UTA,Utah,1628378,Donovan Mitchell,Donovan,G,NaN,36:13,...,1.0,5.0,6.0,9.0,2.0,0.0,2.0,4.0,20.0,-2.0
34830,22100544,1610612762,UTA,Utah,201144,Mike Conley,Mike,G,NaN,27:45,...,2.0,3.0,5.0,3.0,1.0,0.0,3.0,1.0,12.0,0.0

In [42]:
starters_stats = starters[['PLAYER_NAME',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TO',
 'PF',
 'PTS']]
starters_stats

,PLAYER_NAME,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
0,Romeo Langford,1.0,1.0,1.000,0.0,0.0,0.000,0.0,0.0,0.000,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0
1,Jeremy Sochan,7.0,14.0,0.500,2.0,4.0,0.500,7.0,10.0,0.700,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0
2,Jakob Poeltl,6.0,9.0,0.667,0.0,0.0,0.000,1.0,1.0,1.000,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0
3,Devin Vassell,4.0,13.0,0.308,1.0,6.0,0.167,1.0,1.0,1.000,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0
4,Tre Jones,7.0,12.0,0.583,1.0,3.0,0.333,4.0,4.0,1.000,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34826,Bojan Bogdanovic,7.0,14.0,0.500,4.0,10.0,0.400,2.0,2.0,1.000,1.0,5.0,6.0,1.0,1.0,0.0,2.0,0.0,20.0
34827,Royce O'Neale,5.0,7.0,0.714,2.0,4.0,0.500,3.0,4.0,0.750,2.0,2.0,4.0,2.0,0.0,0.0,1.0,3.0,15.0
34828,Rudy Gobert,9.0,10.0,0.900,0.0,0.0,0.000,2.0,4.0,0.500,7.0,12.0,19.0,2.0,0.0,0.0,2.0,4.0,20.0
34829,Donovan Mitchell,4.0,19.0,0.211,2.0,9.0,0.222,10.0,11.0,0.909,1.0,5.0,6.0,9.0,2.0,0.0,2.0,4.0,20.0
34830,Mike Conley,4.0,13.0,0.308,2.0,6.0,0.333,2.0,4.0,0.500,2.0,3.0,5.0,3.0,1.0,0.0,3.0,1.0,12.0

In [51]:
starter_mins = starters[['PLAYER_NAME', 'MIN',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TO',
 'PF',
 'PTS']]
   
starter_mins[starter_mins['PLAYER_NAME'] == 'Stephen Curry']

,PLAYER_NAME,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
1399,Stephen Curry,29:33,11.0,19.0,0.579,5.0,10.0,0.500,11.0,11.0,1.000,1.0,6.0,7.0,7.0,2.0,1.0,3.0,2.0,38.0
1649,Stephen Curry,27:19,6.0,17.0,0.353,3.0,10.0,0.300,5.0,5.0,1.000,2.0,4.0,6.0,1.0,1.0,1.0,2.0,0.0,20.0
2242,Stephen Curry,37:26,12.0,21.0,0.571,6.0,11.0,0.545,2.0,2.0,1.000,1.0,5.0,6.0,7.0,0.0,1.0,4.0,3.0,32.0
3167,Stephen Curry,37:42,3.0,17.0,0.176,2.0,10.0,0.200,4.0,4.0,1.000,0.0,4.0,4.0,6.0,1.0,0.0,3.0,2.0,12.0
3517,Stephen Curry,34:32,10.0,21.0,0.476,8.0,17.0,0.471,2.0,3.0,0.667,0.0,3.0,3.0,10.0,1.0,1.0,4.0,0.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32816,Stephen Curry,38:42,8.0,21.0,0.381,2.0,9.0,0.222,9.0,10.0,0.900,1.0,9.0,10.0,10.0,2.0,0.0,3.0,3.0,27.0
33272,Stephen Curry,36:31,10.0,21.0,0.476,4.0,11.0,0.364,4.0,4.0,1.000,3.0,2.0,5.0,5.0,1.0,0.0,5.0,3.0,28.0
33963,Stephen Curry,36:04,5.0,24.0,0.208,1.0,9.0,0.111,3.0,4.0,0.750,0.0,9.0,9.0,5.0,0.0,1.0,5.0,2.0,14.0
34436,Stephen Curry,32:01,3.0,17.0,0.176,1.0,10.0,0.100,2.0,2.0,1.000,0.0,3.0,3.0,10.0,0.0,1.0,2.0,3.0,9.0
34816,Stephen Curry,35:32,8.0,18.0,0.444,6.0,12.0,0.500,6.0,7.0,0.857,0.0,6.0,6.0,9.0,0.0,1.0,3.0,3.0,28.0

In [65]:
season_2022[['PLAYER_NAME',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TO',
 'PF',
 'PTS']]
starters_2022

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [54]:
starters_avgs = starters_stats.groupby('PLAYER_NAME').mean().reset_index()
starters_avgs

,PLAYER_NAME,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
0,AJ Griffin,5.875000,13.000000,0.460250,2.125000,6.625000,0.361250,0.625000,0.875000,0.375000,0.875000,1.500000,2.375000,1.375000,1.500000,0.250000,1.500000,1.500000,14.500000
1,Aaron Gordon,6.098765,11.172840,0.541333,1.111111,3.246914,0.337383,2.580247,3.641975,0.584185,1.975309,4.308642,6.283951,2.469136,0.703704,0.641975,1.728395,1.975309,15.888889
2,Aaron Holiday,2.375000,7.375000,0.296875,0.500000,2.875000,0.140625,1.375000,1.625000,0.531250,0.750000,1.625000,2.375000,2.625000,1.375000,0.125000,1.125000,1.875000,6.625000
3,Aaron Nesmith,3.444444,7.666667,0.430389,1.444444,4.222222,0.311333,1.277778,1.444444,0.525778,0.777778,3.166667,3.944444,1.055556,1.055556,0.555556,1.000000,3.277778,9.611111
4,Aaron Wiggins,3.705882,8.323529,0.442353,0.852941,2.970588,0.261029,1.470588,1.852941,0.477235,1.470588,3.147059,4.617647,1.735294,0.676471,0.176471,1.235294,2.117647,9.735294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,Zach LaVine,7.371429,16.442857,0.437943,2.557143,6.942857,0.365457,4.385714,5.157143,0.783071,0.385714,3.814286,4.200000,4.485714,0.857143,0.185714,2.514286,2.114286,21.685714
460,Zavier Simpson,4.750000,13.000000,0.354250,0.250000,2.000000,0.083250,1.250000,1.250000,0.500000,0.500000,4.750000,5.250000,7.500000,1.250000,1.000000,2.500000,3.750000,11.000000
461,Zeke Nnaji,3.000000,7.000000,0.429000,0.000000,3.000000,0.000000,2.000000,2.000000,1.000000,3.000000,5.000000,8.000000,1.000000,0.000000,1.000000,3.000000,5.000000,8.000000
462,Ziaire Williams,3.757576,8.060606,0.456515,1.363636,4.272727,0.322455,0.969697,1.151515,0.391424,0.454545,2.090909,2.545455,1.242424,0.636364,0.030303,0.727273,2.030303,9.848485
463,Zion Williamson,8.862069,14.862069,0.595655,0.241379,0.655172,0.149448,5.275862,7.586207,0.712034,1.931034,4.793103,6.724138,4.448276,1.137931,0.551724,2.931034,2.137931,23.241379

In [55]:
starters_avgs[starters_avgs['PLAYER_NAME'] == 'Stephen Curry']

,PLAYER_NAME,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
406,Stephen Curry,8.725,18.8625,0.454037,4.1,10.5125,0.3835,4.3875,4.8375,0.832275,0.4875,5.1875,5.675,6.4125,1.0625,0.2875,2.975,2.1875,25.9375

In [45]:

highest_FGM = starters_avgs.sort_values(by='FGM', ascending=False)
highest_FGM

,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
PLAYER_NAME,,,,,,,,,,,,,,,,,,
LeBron James,11.017241,21.706897,0.503224,2.431034,7.379310,0.311621,4.275862,5.775862,0.728707,1.258621,7.120690,8.379310,5.948276,1.034483,0.793103,3.206897,1.931034,28.741379
Cam Thomas,11.000000,18.000000,0.611000,4.000000,8.000000,0.500000,1.000000,1.000000,1.000000,1.000000,3.000000,4.000000,0.000000,2.000000,0.000000,1.000000,3.000000,27.000000
Giannis Antetokounmpo,10.923077,20.294872,0.541692,0.910256,3.294872,0.262872,8.602564,12.294872,0.696667,2.038462,9.871795,11.910256,5.653846,0.948718,1.102564,3.602564,3.371795,31.358974
Luka Doncic,10.377778,21.977778,0.470956,3.133333,8.822222,0.345644,6.755556,8.988889,0.743111,0.811111,8.277778,9.088889,8.311111,1.444444,0.600000,4.066667,2.411111,30.644444
Joel Embiid,10.179487,19.858974,0.510218,1.153846,3.500000,0.303244,9.653846,11.666667,0.814192,2.102564,9.115385,11.217949,4.051282,1.000000,1.410256,3.512821,2.961538,31.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Jaylin Williams,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,4.000000,0.250000,0.000000,11.000000,11.000000,2.000000,0.000000,1.000000,0.000000,3.000000,1.000000
Yuta Watanabe,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,0.000000,0.500000,0.000000,0.500000,0.000000,0.000000
Elfrid Payton,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.500000,1.000000,3.000000,4.000000,2.000000,3.000000,2.000000,3.000000,1.000000,1.000000
Keljin Blevins,0.000000,3.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,2.000000,5.000000,1.000000,0.000000,1.000000,1.000000,0.000000
Udonis Haslem,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000

In [46]:
higest_FGA = starters_avgs.sort_values(by='FGA', ascending=False)
higest_FGA

,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
PLAYER_NAME,,,,,,,,,,,,,,,,,,
Luka Doncic,10.377778,21.977778,0.470956,3.133333,8.822222,0.345644,6.755556,8.988889,0.743111,0.811111,8.277778,9.088889,8.311111,1.444444,0.600000,4.066667,2.411111,30.644444
LeBron James,11.017241,21.706897,0.503224,2.431034,7.379310,0.311621,4.275862,5.775862,0.728707,1.258621,7.120690,8.379310,5.948276,1.034483,0.793103,3.206897,1.931034,28.741379
Devin Booker,9.937500,21.100000,0.462838,2.600000,7.037500,0.372762,5.275000,6.075000,0.836000,0.700000,4.137500,4.837500,5.100000,1.012500,0.400000,2.425000,2.812500,27.750000
Ja Morant,10.000000,21.071429,0.472071,1.542857,4.800000,0.293500,6.457143,8.685714,0.726314,1.328571,4.900000,6.228571,7.414286,1.157143,0.385714,3.600000,1.742857,28.000000
Donovan Mitchell,9.356164,20.397260,0.462123,3.561644,9.356164,0.372493,4.657534,5.397260,0.799671,0.863014,3.369863,4.232877,5.095890,1.273973,0.260274,2.904110,2.602740,26.931507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Dewayne Dedmon,1.000000,2.000000,0.500000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,5.000000,0.000000,0.000000,1.000000,2.000000,4.000000,2.000000
Yuta Watanabe,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,0.000000,0.500000,0.000000,0.500000,0.000000,0.000000
Ed Davis,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,1.000000,2.000000,4.000000,6.000000,2.000000,0.000000,0.000000,0.000000,5.000000,2.000000
Nerlens Noel,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,3.000000,10.000000,13.000000,1.000000,2.000000,0.000000,0.000000,4.000000,2.000000
Jaylin Williams,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,4.000000,0.250000,0.000000,11.000000,11.000000,2.000000,0.000000,1.000000,0.000000,3.000000,1.000000

In [48]:
highest_FG_PCT = starters_avgs.sort_values(by='FG_PCT', ascending=False)
highest_FG_PCT

,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS
PLAYER_NAME,,,,,,,,,,,,,,,,,,
Nerlens Noel,1.0,1.000000,1.000000,0.0,0.0,0.00,0.0,3.000000,0.000000,3.000000,10.000000,13.0,1.000000,2.000000,0.000000,0.000000,4.000000,2.0
Jordan McLaughlin,5.0,6.000000,0.833000,2.0,2.0,1.00,0.0,0.000000,0.000000,0.000000,1.000000,1.0,4.000000,4.000000,0.000000,1.000000,4.000000,12.0
Marques Bolden,9.0,11.000000,0.818000,3.0,4.0,0.75,0.0,0.000000,0.000000,2.000000,3.000000,5.0,2.000000,1.000000,2.000000,1.000000,4.000000,21.0
Jericho Sims,3.0,3.857143,0.809571,0.0,0.0,0.00,1.0,1.714286,0.261857,2.714286,5.285714,8.0,1.285714,0.714286,1.428571,1.142857,3.428571,7.0
Walker Kessler,4.6,5.800000,0.802200,0.0,0.0,0.00,0.6,1.600000,0.250000,3.600000,5.800000,9.4,0.800000,0.400000,2.200000,1.000000,3.400000,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Jaylin Williams,0.0,1.000000,0.000000,0.0,1.0,0.00,1.0,4.000000,0.250000,0.000000,11.000000,11.0,2.000000,0.000000,1.000000,0.000000,3.000000,1.0
Yuta Watanabe,0.0,2.000000,0.000000,0.0,1.0,0.00,0.0,0.000000,0.000000,0.000000,0.500000,0.5,0.000000,0.500000,0.000000,0.500000,0.000000,0.0
Keljin Blevins,0.0,3.000000,0.000000,0.0,3.0,0.00,0.0,0.000000,0.000000,2.000000,0.000000,2.0,5.000000,1.000000,0.000000,1.000000,1.000000,0.0
Elfrid Payton,0.0,3.000000,0.000000,0.0,0.0,0.00,1.0,2.000000,0.500000,1.000000,3.000000,4.0,2.000000,3.000000,2.000000,3.000000,1.000000,1.0
Ed Davis,0.0,2.000000,0.000000,0.0,0.0,0.00,2.0,2.000000,1.000000,2.000000,4.000000,6.0,2.000000,0.000000,0.000000,0.000000,5.000000,2.0

In [36]:
starters['PLAYER_NAME'].unique()

array(['Romeo Langford', 'Jeremy Sochan', 'Jakob Poeltl', 'Devin Vassell',
       'Tre Jones', 'Trey Murphy III', 'Naji Marshall',
       'Jonas Valanciunas', 'Herbert Jones', 'CJ McCollum',
       'Corey Kispert', 'Kyle Kuzma', 'Daniel Gafford', 'Bradley Beal',
       'Monte Morris', 'Lauri Markkanen', 'Jarred Vanderbilt',
       'Walker Kessler', 'Jordan Clarkson', 'Mike Conley',
       'MarJon Beauchamp', 'Giannis Antetokounmpo', 'Brook Lopez',
       'Grayson Allen', 'Jrue Holiday', 'Isaac Okoro', 'Evan Mobley',
       'Jarrett Allen', 'Donovan Mitchell', 'Darius Garland',
       'Bojan Bogdanovic', 'Isaiah Stewart', 'Jalen Duren', 'Jaden Ivey',
       'Killian Hayes', 'Tobias Harris', 'P.J. Tucker', 'Joel Embiid',
       "De'Anthony Melton", 'James Harden', 'DeMar DeRozan',
       'Patrick Williams', 'Nikola Vucevic', 'Zach LaVine', 'Alex Caruso',
       "De'Andre Hunter", 'John Collins', 'Onyeka Okongwu',
       'Dejounte Murray', 'Trae Young', 'Buddy Hield', 'Aaron Nesmith',
       'Myles Turner', 'Andrew Nembhard', 'Tyrese Haliburton',
       'Jaylen Brown', 'Jayson Tatum', 'Al Horford', 'Derrick White',
       'Payton Pritchard', 'Jonathan Kuminga', 'Draymond Green',
       'Kevon Looney', 'Moses Moody', 'Jordan Poole', 'Kevin Durant',
       "Royce O'Neale", 'Nic Claxton', 'Joe Harris', 'Ben Simmons',
       'O.G. Anunoby', 'Pascal Siakam', 'Juancho Hernangomez',
       'Scottie Barnes', 'Fred VanVleet', 'RJ Barrett', 'Julius Randle',
       'Mitchell Robinson', 'Jalen Brunson', 'Immanuel Quickley',
       'Paolo Banchero', 'Bol Bol', 'Moritz Wagner', 'Franz Wagner',
       'Markelle Fultz', 'Eric Gordon', 'Jabari Smith Jr.',
       'Alperen Sengun', 'Jalen Green', 'Kevin Porter Jr.',
       'Tim Hardaway Jr.', 'Reggie Bullock', 'Christian Wood',
       'Spencer Dinwiddie', 'Luka Doncic', 'Anthony Edwards',
       'Jaden McDaniels', 'Rudy Gobert', 'Austin Rivers',
       "D'Angelo Russell", 'Josh Hart', 'Jerami Grant', 'Jusuf Nurkic',
       'Anfernee Simons', 'Damian Lillard', 'Luguentz Dort',
       'Jalen Williams', 'Aleksej Pokusevski', 'Josh Giddey',
       'Shai Gilgeous-Alexander', 'Lonnie Walker IV', 'LeBron James',
       'Thomas Bryant', 'Patrick Beverley', 'Dennis Schroder',
       'Harrison Barnes', 'Keegan Murray', 'Domantas Sabonis',
       'Kevin Huerter', "De'Aaron Fox", 'Gordon Hayward',
       'P.J. Washington', 'Mason Plumlee', 'Kelly Oubre Jr.',
       'LaMelo Ball', 'Kawhi Leonard', 'Marcus Morris Sr.', 'Ivica Zubac',
       'Paul George', 'Reggie Jackson', 'Max Strus', 'Haywood Highsmith',
       'Bam Adebayo', 'Tyler Herro', 'Victor Oladipo', 'Klay Thompson',
       'Quentin Grimes', 'Deni Avdija', 'Mikal Bridges', 'Torrey Craig',
       'Deandre Ayton', 'Damion Lee', 'Chris Paul', 'Dillon Brooks',
       'Jaren Jackson Jr.', 'Steven Adams', 'John Konchar', 'Ja Morant',
       'Christian Braun', 'Aaron Gordon', 'Nikola Jokic',
       'Kentavious Caldwell-Pope', 'Bruce Brown', 'Bogdan Bogdanovic',
       'Keita Bates-Diop', 'Dorian Finney-Smith', 'Naz Reid',
       'Zion Williamson', 'Drew Eubanks', 'Aaron Wiggins',
       'Troy Brown Jr.', 'Grant Williams', 'Marcus Smart', 'Kyrie Irving',
       'Donte DiVincenzo', 'Christian Koloko', 'Kyle Anderson',
       'Terry Rozier', 'Jamal Murray', 'Kristaps Porzingis',
       'Austin Reaves', 'Nicolas Batum', 'Moussa Diabate', 'John Wall',
       'Jimmy Butler', 'Nikola Jovic', 'Keldon Johnson', 'Kemba Walker',
       'Justise Winslow', 'Kelly Olynyk', 'Bobby Portis', 'Jevon Carter',
       'Eugene Omoruyi', 'Isaiah Joe', 'Bismack Biyombo', 'Devin Booker',
       'Trent Forrest', 'Jalen McDaniels', 'Jalen Smith', 'Lamar Stevens',
       'Matisse Thybulle', 'Dwight Powell', 'Anthony Davis',
       'Caleb Martin', 'Udonis Haslem', 'Khris Middleton', 'Amir Coffey',
       'Moses Brown', 'Terance Mann', 'Stephen Curry', 'Jalen Johnson',
       'Clint Capela', 'AJ Griffin', 'Terence Davis', 'Thaddeus Young',
       'Gary Trent Jr.', 'Kyle Lowry', 'Darius Bazley', 'Charles Bassey',
       'Josh Richardson', 'Taj Gibson', 'Landry Shamet', 'Blake Griffin',
       'Jordan Goodwin', 'Brandon Clarke', 'Tyus Jones', 'Isaiah Roby',
       'Zach Collins', 'Dario Saric', 'Dyson Daniels', 'Davion Mitchell',
       'Ayo Dosunmu', 'Malaki Branham', 'Kessler Edwards',
       'Markieff Morris', "Day'Ron Sharpe", 'Patty Mills',
       'Edmond Sumner', 'Jeremiah Robinson-Earl', 'Caris LeVert',
       'Malik Beasley', 'Talen Horton-Tucker', 'Nickeil Alexander-Walker',
       'Aaron Holiday', 'Dru Smith', 'Juan Toscano-Anderson',
       'Marvin Bagley III', 'JaMychal Green', 'Ty Jerome',
       'Collin Sexton', 'Jordan Nwora', 'Santi Aldama', 'David Roddy',
       'Ish Wainright', 'Cameron Payne', 'Bennedict Mathurin',
       'Mamadi Diakite', 'Wendell Moore Jr.', 'Kenyon Martin Jr.',
       'Andrew Wiggins', 'Trendon Watford', 'Jarrett Culver', 'Dean Wade',
       'Shake Milton', 'Javonte Green', 'Isaiah Livers', 'Gary Harris',
       'Jose Alvarado', 'Karl-Anthony Towns', 'Theo Maledon',
       'Caleb Houstan', 'Robin Lopez', 'Saddiq Bey', 'Rodney McGruder',
       'Montrezl Harrell', 'Mo Bamba', 'Jalen Suggs', 'Bruno Fernando',
       'Brandon Ingram', 'Malachi Flynn', 'Davon Reed',
       'Michael Porter Jr.', 'Chuma Okeke', 'Shaedon Sharpe',
       'Anthony Lamb', 'Kenrich Williams', 'Isaiah Hartenstein',
       'Jeff Green', 'DeAndre Jordan', 'Gorgui Dieng', 'Danuel House Jr.',
       'Tyrese Maxey', 'Wendell Carter Jr.', 'Cam Reddish',
       'Dalano Banton', 'Josh Green', 'Luke Kennard', 'Otto Porter Jr.',
       'Kevin Love', 'Cory Joseph', 'Desmond Bane', 'Wenyen Gabriel',
       'Anthony Gill', 'Dennis Smith Jr.', 'Cade Cunningham',
       'Jericho Sims', 'JaVale McGee', 'Kendrick Nunn', 'Mike Muscala',
       'Chris Duarte', 'Cameron Johnson', 'Evan Fournier',
       'Terrence Ross', "Jae'Sean Tate", 'Isaiah Jackson', 'Tre Mann',
       'Damian Jones', 'Norman Powell', 'Cole Anthony',
       'Russell Westbrook', 'KZ Okpala', 'Noah Vonleh', 'Usman Garuba',
       'Terry Taylor', 'T.J. McConnell', 'Cedi Osman', 'Raul Neto',
       'Precious Achiuwa', 'Khem Birch', 'Will Barton', 'Max Christie',
       'Malik Monk', 'Jaylin Williams', 'Willy Hernangomez', 'Trey Lyles',
       'Jock Landale', 'Josh Okogie', 'Duane Washington Jr.',
       'Sandro Mamukelashvili', 'Marques Bolden', 'Dalen Terry',
       'Coby White', 'Keon Johnson', 'James Wiseman', 'Dewayne Dedmon',
       'Gabe Vincent', 'Bones Hyland', 'Derrick Jones Jr.',
       "Devonte' Graham", 'Pat Connaughton', 'Sam Hauser',
       'Duncan Robinson', 'Orlando Robinson', 'Marcus Garrett',
       'Jaden Hardy', 'Scotty Pippen Jr.', 'Jaylen Nowell',
       'Omer Yurtseven', 'Paul Reed', 'Rui Hachimura', 'Ziaire Williams',
       'Kennedy Chandler', 'Robert Williams III', 'Daniel Theis',
       'Wesley Matthews', 'Jae Crowder', 'Danny Green', 'Xavier Tillman',
       'Gary Payton II', 'Jaxson Hayes', 'Andre Drummond', 'Seth Curry',
       'Danilo Gallinari', 'Miles Bridges', 'Joshua Primo',
       'Oshae Brissett', 'Tomas Satoransky', 'Thanasis Antetokounmpo',
       'Garrison Mathews', 'Armoni Brooks', 'Alec Burks', 'Obi Toppin',
       'Mychal Mulder', 'R.J. Hampton', 'Frank Jackson',
       'Tristan Thompson', 'Stanley Johnson', 'DeMarcus Cousins',
       'Bryn Forbes', 'Georgios Kalaitzakis', 'Jaylen Hoard',
       'Vit Krejci', 'Zavier Simpson', 'Robert Covington',
       'Justin Holiday', 'CJ Elleby', 'Didi Louzada', 'Reggie Perry',
       'Brandon Williams', 'Greg Brown III', 'Dwight Howard', 'Kris Dunn',
       'Timothe Luwawu-Cabarrot', 'Avery Bradley', 'Goga Bitadze',
       'Ignas Brazdeikis', 'Serge Ibaka', 'Trevor Ariza',
       'Justin Anderson', 'Delon Wright', 'Keifer Sykes', 'Elijah Hughes',
       'Eric Paschall', 'George Hill', 'Georges Niang', 'Paul Millsap',
       'Goran Dragic', 'Elfrid Payton', 'Maxi Kleber', 'Olivier Sarr',
       'Malcolm Brogdon', 'Doug McDermott', 'Hassan Whiteside',
       'Lindy Waters III', 'Tony Snell', 'Alex Len', 'Chris Boucher',
       'Furkan Korkmaz', 'Keljin Blevins', 'James Johnson',
       'LaMarcus Aldridge', 'Brandon Goodwin', 'Maurice Harkless',
       'Rajon Rondo', 'Derrick Favors', 'OG Anunoby', 'Udoka Azubuike',
       'Hamidou Diallo', 'Cam Thomas', 'Ben McLemore', 'Chimezie Metu',
       'Lance Stephenson', "DeAndre' Bembry", 'Richaun Holmes',
       'Zeke Nnaji', 'Cody Martin', 'Joe Ingles', 'Jordan McLaughlin',
       'Garrett Temple', 'Wayne Ellington', 'Nassir Little',
       'Nerlens Noel', 'Ed Davis', 'Rudy Gay', 'Tyler Cook',
       'Charlie Brown Jr.', 'Alfonzo McKinnie', 'Yuta Watanabe',
       'Lonzo Ball', 'David Duke Jr.', 'Killian Tillie',
       'Freddie Gillespie', 'Jared Butler', 'Eric Bledsoe',
       'Facundo Campazzo', 'Larry Nance Jr.', 'Tim Frazier',
       'Skylar Mays', 'Miles McBride', 'Kevin Pangos', 'Luka Garza',
       'Cassius Stanley', 'Derrick Walton Jr.', 'David Nwaba'],
      dtype=object)

In [32]:
games_details_2022

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,22200477,1610612759,SAS,San Antonio,1629641,Romeo Langford,Romeo,F,NaN,18:06,...,1.0,1.0,2.0,0.0,1.0,0.0,2.0,5.0,2.0,-2.0
1,22200477,1610612759,SAS,San Antonio,1631110,Jeremy Sochan,Jeremy,F,NaN,31:01,...,6.0,3.0,9.0,6.0,1.0,0.0,2.0,1.0,23.0,-14.0
2,22200477,1610612759,SAS,San Antonio,1627751,Jakob Poeltl,Jakob,C,NaN,21:42,...,1.0,3.0,4.0,1.0,1.0,0.0,2.0,4.0,13.0,-4.0
3,22200477,1610612759,SAS,San Antonio,1630170,Devin Vassell,Devin,G,NaN,30:20,...,0.0,9.0,9.0,5.0,3.0,0.0,2.0,1.0,10.0,-18.0
4,22200477,1610612759,SAS,San Antonio,1630200,Tre Jones,Tre,G,NaN,27:44,...,0.0,2.0,2.0,3.0,0.0,0.0,2.0,2.0,19.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34834,22100544,1610612762,UTA,Utah,1630215,Jared Butler,Jared,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34835,22100544,1610612762,UTA,Utah,1630238,Malik Fitts,Malik,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34836,22100544,1610612762,UTA,Utah,1630235,Trent Forrest,Trent,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34837,22100544,1610612762,UTA,Utah,1630190,Elijah Hughes,Elijah,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34838,22100544,1610612762,UTA,Utah,1629671,Miye Oni,Miye,NaN,DNP - Coach's Decision,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
games_details_2022['START_POSITION'].unique()

array(['F', 'C', 'G', nan], dtype=object)